name: Python Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pip install .
        python -m unittest discover -s tests

    - name: Coveralls
      uses: coverallsapp/github-action@v1
      with:
        github-token: ${{ secrets.token_github }}
        repo-token: ${{ secrets.cov_github_token }}

    - name: Update GitHub Status
      uses: actions/github/status@v1
      with:
        status: success
        description: ${{ steps.coveralls.outputs.percentage }}%
